Ansible 3
Otus-DevOps-2021-11/yunusovtr_infra pull request #9
Opened 2022-01-31 15:15 UTC by yunusovtr

# Выполнено ДЗ № 12: Ansible: работа с ролями и окружениями

 - [x] Основное ДЗ
 - [x] Задание со *

## В процессе сделано:
 - Выполнены действия в соответствии с методичкой
 - Самостоятельное задание выполнено
   - В открытии порта 80 не было необходимости
   - Добавлен вызов роли jdauphant.nginx в плейбук app.yml
   - Работа site-yml проверена - работает
 - Ошибка линтёра при сдаче видимо связана с нежеланием ansible-lint обрабатывать относительные пути в опции --exclude, из-за чего роль jdauphant.nginx всё-таки проверяется, а в ней ошибка - роль имеет повторяющийся when в одном из тасков. Надо б исправить в тестах!!!
 - Действия с Ansible Vault в соответствии с методичкой проведены, пользователи успешно создаются
 - Задание со *: Работа с динамическими инвентори.
   - Выполнено через добавление ресурса local_file, генерирующего Ansible инвентори при применении конфигурации terraform через шаблон в файле terraform/{environment}/inventory.tftpl.
   - Окружение задаётся через переменную терраформа, также создающую ВМ с разными именами для разных окружений.
   - Переменная db_host также переопределяется на уровне инвентори

## Как запустить проект:
 - cd terraform/stage && terraform apply -auto-approve
 - cd ../../ansible/ && ansible-playbook site.yml

## Как проверить работоспособность:
 - перейти по ссылке http://<external_ip_address_app>

## PR checklist
 - [ ] Выставил label с номером домашнего задания
 - [ ] Выставил label с темой домашнего задания

2022-01-31 17:59 UTC, mrgreyves requested changes
Здравствуйте!)
Рекомендую ознакомиться с результатами тестов
Там не страшно, в манифестах ansible вам нужно удалить Trailing whitespaces - пробелы после конца слов в общем ^_^

2022-01-31 18:26 UTC, yunusovtr commented
Линтёр Ансибла считает вайтспейсами символ возврата каретки ((( Поправил, но погрустил

2022-01-31 18:27 UTC, yunusovtr commented
> Здравствуйте!) Рекомендую ознакомиться с результатами тестов Там не страшно, в манифестах ansible вам нужно удалить Trailing whitespaces - пробелы после конца слов в общем ^_^

Линтёр Ансибла считает вайтспейсами символ возврата каретки ((( Поправил, но погрустил

2022-02-01 08:49 UTC, mrgreyves approved these changes
Здравствуйте!)
Проверил ваше дз
ДЗ конечно же принимаю ^_^

2022-02-01 15:11 UTC, merged